### PR TITLE
Made grammar corrections

### PR DESCRIPTION
**Pull request by Jimmyzs**
Its is the possessive form of it.
Made changes for sentence agreement.

### CODE REVIEW

**Comment by Jimmyzs** [comment]
Added the edits for week 2

**Comment by f0cus10** [comment]
Good changes Jimmy. Will pull it onto the repo very soon.

**Comment by f0cus10** [comment]
Thanks for the changes, Jimmy. They were very constructive and *a lot* of grammar errors missed my eye.

**Comment by f0cus10** [comment]
Yeah, I'm re-opening this

**Pull request merged**
